export const RETURN_FILTER = {
	listingId: 1,
	deviceCondition: 1,
	defaultImage: 1,
	listingLocation: 1,
	listingPrice: 1,
	marketingName: 1,
	model: 1,
	listingDate: 1,
	listedBy: 1,
	verified: 1,
	verifiedDate: 1,
	deviceStorage: 1,
	deviceRam: 1,
	status: 1,
	isOtherVendor: 1,
	imagePath: 1,
};

export const VENDORS: { [key: number]: string } = {
	6: 'Amazon',
	7: 'Quikr',
	8: 'Cashify',
	9: '2Gud',
	10: 'Budli',
	11: 'Paytm',
	12: 'Yaantra',
	13: 'Sahivalue',
	14: 'Shopcluse',
	15: 'Xtracover',
	16: 'Mobigarage',
	17: 'Instacash',
	18: 'Cashforphone',
	19: 'Recycledevice',
	20: 'Quickmobile',
	21: 'mbr_Buyblynk',
	22: 'mbr_Electronicbazaar',
	23: 'Flipkart',
	26: 'OLX',
};
